root: true
env:
  browser: true
  es6: true
  jest: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
globals:
  Atomics: "readonly"
  SharedArrayBuffer: "readonly"
ignorePatterns:
  - dist/*
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
settings:
  import/extensions:
    - ".js"
    - ".jsx"
    - ".ts"
    - ".tsx"
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
  import/resolver:
    node:
      extensions:
        - ".js"
        - ".jsx"
        - ".ts"
        - ".tsx"
rules:
  import/extensions: "off"
  import/no-unresolved: "off"
  import/prefer-default-export: "off"
  comma-dangle: "off"
  class-methods-use-this: "off"
  semi: "error"
  no-unused-vars: "off"
  no-use-before-define: "off"
  no-constant-condition:
    - "error"
    - checkLoops: false
  object-curly-newline: "off"
  no-restricted-syntax:
    ["error", "ForInStatement", "LabeledStatement", "WithStatement"]
  no-await-in-loop: "off"
  no-bitwise: "off"
